# Generated by Django 5.0.7 on 2024-07-11 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_businessprofile_facebook_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.CharField(max_length=20)),
                ('tuesday', models.CharField(max_length=20)),
                ('wednesday', models.CharField(max_length=20)),
                ('thursday', models.CharField(max_length=20)),
                ('friday', models.CharField(max_length=20)),
                ('saturday', models.CharField(max_length=20)),
                ('sunday', models.CharField(max_length=20)),
                ('kitchen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='Auth.businessprofile')),
            ],
        ),
    ]
