# Generated by Django 5.0.7 on 2024-07-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_useraddress_latitude_useraddress_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='tiffin_price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
