# Generated by Django 5.0.7 on 2024-07-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_categoryitem_meal_dayplan_weeklyplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayplan',
            name='breakfast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakfast_dayplans', to='kitchen.meal'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='dinner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_dayplans', to='kitchen.meal'),
        ),
        migrations.AlterField(
            model_name='dayplan',
            name='lunch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_dayplans', to='kitchen.meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='items',
            field=models.ManyToManyField(related_name='meals', to='kitchen.categoryitem'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='plans',
            field=models.ManyToManyField(related_name='weekly_plans', to='kitchen.dayplan'),
        ),
    ]
