# Generated by Django 5.0.7 on 2024-07-14 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_useraddress_latitude_useraddress_longitude'),
        ('kitchen', '0005_todaymeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('banner', models.CharField(max_length=200)),
                ('coupan_code', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('discount_value', models.CharField(max_length=100)),
                ('discount_unit', models.CharField(max_length=100)),
                ('total_uses', models.CharField(max_length=100)),
                ('uses_per_customer', models.CharField(max_length=100)),
                ('minimum_spend_value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_day', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='Auth.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=False)),
                ('meal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_quantity', models.IntegerField()),
                ('total_meal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.userprofile')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='kitchen.discount')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='kitchen.scheduleorder')),
            ],
        ),
    ]
