# Generated by Django 5.0.7 on 2024-07-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0006_discount_extrameal_scheduleorder_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='banner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
