# Generated by Django 5.0.7 on 2024-07-14 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_useraddress_latitude_useraddress_longitude'),
        ('kitchen', '0007_alter_discount_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='kitchen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.businessprofile'),
        ),
    ]
