# Generated by Django 5.0.7 on 2024-07-16 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_useraddress_latitude_useraddress_longitude'),
        ('kitchen', '0008_subscription_kitchen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyplan',
            name='plans',
        ),
        migrations.AddField(
            model_name='extrameal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.userprofile'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='breakfast',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='dinner',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='lunch',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Weekly_plan', to='Auth.businessprofile'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=100)),
                ('extra', models.JSONField(default=list)),
                ('menu', models.JSONField(default=list)),
                ('meal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_quantity', models.IntegerField()),
                ('addon_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_coupan_code', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_meal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(max_length=100)),
                ('schedule', models.JSONField(default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='Auth.userprofile')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_orders', to='Auth.businessprofile')),
            ],
        ),
    ]
