# Generated by Django 5.0.7 on 2024-07-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0011_rename_breakfast_weeklyplan_plans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
