# Generated by Django 5.0.7 on 2024-07-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0012_weeklyplan_created_at_weeklyplan_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='items',
        ),
        migrations.RemoveField(
            model_name='dayplan',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='dayplan',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='dayplan',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='extrameal',
            name='user',
        ),
        migrations.AddField(
            model_name='todaymeal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todaymeal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='todaymeal',
            name='menu',
        ),
        migrations.DeleteModel(
            name='CategoryItem',
        ),
        migrations.DeleteModel(
            name='DayPlan',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='ExtraMeal',
        ),
        migrations.AddField(
            model_name='todaymeal',
            name='menu',
            field=models.JSONField(default=list),
        ),
    ]
