# Generated by Django 5.0.7 on 2024-07-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0013_remove_meal_items_remove_dayplan_breakfast_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaymeal',
            name='time_of_day',
        ),
    ]
