# Generated by Django 5.0.7 on 2024-07-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0015_rename_menu_todaymeal_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaymeal',
            name='plans',
        ),
        migrations.AddField(
            model_name='todaymeal',
            name='menu',
            field=models.ManyToManyField(related_name='today_meal_menu', to='kitchen.menuitem'),
        ),
        migrations.AddField(
            model_name='todaymeal',
            name='times_of_day',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
