# Generated by Django 5.0.7 on 2024-07-16 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0016_remove_todaymeal_plans_todaymeal_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleorder',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='scheduleorder',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='scheduleorder',
            name='time_of_day',
        ),
        migrations.AddField(
            model_name='discount',
            name='flag',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='users',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scheduleorder',
            name='breakfast',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='scheduleorder',
            name='dinner',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='scheduleorder',
            name='lunch',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_menu', to='kitchen.weeklyplan'),
        ),
    ]
