# Generated by Django 5.0.7 on 2024-07-16 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0017_remove_scheduleorder_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='schedule',
        ),
        migrations.AddField(
            model_name='subscription',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_subscription', to='kitchen.scheduleorder'),
        ),
    ]
