# Generated by Django 5.0.7 on 2024-07-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0019_subscription_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='total_meal_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
