# Generated by Django 5.0.7 on 2024-07-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0021_menuitem_is_active_alter_order_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='brekfast',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='dinner',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lunch',
            field=models.IntegerField(default=0),
        ),
    ]
