# Generated by Django 5.0.7 on 2024-07-17 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_businessprofile_tiffin_price'),
        ('kitchen', '0022_subscription_brekfast_subscription_dinner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_coupan_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AddField(
            model_name='order',
            name='oprating_hours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Auth.operatinghours'),
        ),
    ]
