# Generated by Django 5.0.7 on 2024-07-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0023_remove_order_discount_coupan_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_menu', to='kitchen.weeklyplan'),
        ),
    ]
