# Generated by Django 5.0.7 on 2024-07-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0024_alter_order_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oprating_hours',
        ),
    ]
