# Generated by Django 5.0.7 on 2024-07-18 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_businessprofile_tiffin_price'),
        ('kitchen', '0025_remove_order_oprating_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('cancel_time', models.CharField(max_length=100)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.businessprofile')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CancelOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('cancel_time', models.CharField(max_length=100)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.businessprofile')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kitchen.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Auth.userprofile')),
            ],
        ),
    ]
