# Generated by Django 5.0.7 on 2024-07-18 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0026_cancellsubscription_cancelorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancel_order', to='kitchen.order'),
        ),
    ]
